apiVersion: v1
kind: ReplicationController
metadata:
 name: nginx-rc
 namespace: quota-demo-ns
spec:
 replicas: 3
 selector:
    app: nginx
 template:
    metadata:
      name:  nginx-pod
      labels:
        app: nginx
        tier: dev
    spec:
      containers:
      - name: nginx-container
        image: nginx
        imagePullPolicy: Always
        resources:
                limits:
                        memory: "100Mi"
  
        ports:
        - containerPort: 80

